openapi: 3.0.0
info:
  title: API
  version: 1.0.0
paths:
  /tasks:
    get:
      summary: Get all tasks
      tags:
        - tasks
      responses:
        '200':
          description: A list of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    post:
      summary: Create a new task
      tags:
        - tasks
      requestBody:
        description: The task to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostTaskRequestBody'
      responses:
        '201':
          description: The created task
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
  /tasks/{id}:
    patch:
      summary: Update an existing task
      tags:
        - tasks
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the task to update (required)
          schema:
            type: integer
            format: uint
      requestBody:
        description: The task data to update (ID is provided in the URL)
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchTaskRequestBody'
      responses:
        '200':
          description: The updated task
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
    delete:
      summary: Delete a task by ID
      tags:
        - tasks
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the task to delete
          schema:
            type: integer
            format: uint
      responses:
        '204':
          description: Task deleted successfully

components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
          format: uint
          description: The unique identifier for the task.
        task:
          type: string
          description: The description of the task.
        is_done:
          type: boolean
          description: Indicates whether the task is completed.
        message:
          type: string
          description: Additional message related to the task.
        text:
          type: string
          description: Additional text related to the task.

    PostTaskRequestBody:
      type: object
      properties:
        task:
          type: string
          description: The new task description (required).
        is_done:
          type: boolean
          description: The completion status of the task (optional).

    PatchTaskRequestBody:
      type: object
      properties:
        task:
          type: string
          description: The new task description (optional).
        is_done:
          type: boolean
          description: The completion status of the task (optional).